# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5b0dc416aba55633f8c832353727d5686e49095176dc4023bc644f3147281a88d3c16b80bd6a07760554b52fe1c91ff03c6d984a3d44a422f065a1738ead694

test:
  secret_key_base: 8db76a5d38db3d90bf7e43dc5da03794953f61a749f098220bc83c623f23159a7269f9173fc9e1419642ad4c14183c6114e3f3c6df7ea549f1ed1c7bcb602d08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
